//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KermesseApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_arqueocajadet
    {
        public int id_ArqueoCaja { get; set; }
        public string nombre { get; set; }
        public string valor { get; set; }
        public decimal cantidad { get; set; }
        public string subtotal { get; set; }
        public int id_arqueocaja_det { get; set; }
    }
}
